/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BarberRouteImport } from './routes/barber'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarberLoginRouteImport } from './routes/barber/login'
import { Route as BarberDashboardRouteImport } from './routes/barber/dashboard'
import { Route as BarberAgendaRouteImport } from './routes/barber/agenda'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminFinanceiroRouteImport } from './routes/admin/financeiro'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminComissoesRouteImport } from './routes/admin/comissoes'
import { Route as AdminBarbersRouteImport } from './routes/admin/barbers'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberRoute = BarberRouteImport.update({
  id: '/barber',
  path: '/barber',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberLoginRoute = BarberLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BarberRoute,
} as any)
const BarberDashboardRoute = BarberDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BarberRoute,
} as any)
const BarberAgendaRoute = BarberAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => BarberRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComissoesRoute = AdminComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBarbersRoute = AdminBarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/barber': typeof BarberRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/barbers': typeof AdminBarbersRoute
  '/admin/comissoes': typeof AdminComissoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/barber/agenda': typeof BarberAgendaRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/login': typeof BarberLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/barber': typeof BarberRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/barbers': typeof AdminBarbersRoute
  '/admin/comissoes': typeof AdminComissoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/barber/agenda': typeof BarberAgendaRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/login': typeof BarberLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/barber': typeof BarberRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/barbers': typeof AdminBarbersRoute
  '/admin/comissoes': typeof AdminComissoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/barber/agenda': typeof BarberAgendaRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/login': typeof BarberLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/barber'
    | '/login'
    | '/signup'
    | '/admin/appointments'
    | '/admin/barbers'
    | '/admin/comissoes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/services'
    | '/admin/usuarios'
    | '/barber/agenda'
    | '/barber/dashboard'
    | '/barber/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/barber'
    | '/login'
    | '/signup'
    | '/admin/appointments'
    | '/admin/barbers'
    | '/admin/comissoes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/services'
    | '/admin/usuarios'
    | '/barber/agenda'
    | '/barber/dashboard'
    | '/barber/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/barber'
    | '/login'
    | '/signup'
    | '/admin/appointments'
    | '/admin/barbers'
    | '/admin/comissoes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/services'
    | '/admin/usuarios'
    | '/barber/agenda'
    | '/barber/dashboard'
    | '/barber/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BarberRoute: typeof BarberRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber': {
      id: '/barber'
      path: '/barber'
      fullPath: '/barber'
      preLoaderRoute: typeof BarberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/login': {
      id: '/barber/login'
      path: '/login'
      fullPath: '/barber/login'
      preLoaderRoute: typeof BarberLoginRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/dashboard': {
      id: '/barber/dashboard'
      path: '/dashboard'
      fullPath: '/barber/dashboard'
      preLoaderRoute: typeof BarberDashboardRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/agenda': {
      id: '/barber/agenda'
      path: '/agenda'
      fullPath: '/barber/agenda'
      preLoaderRoute: typeof BarberAgendaRouteImport
      parentRoute: typeof BarberRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comissoes': {
      id: '/admin/comissoes'
      path: '/comissoes'
      fullPath: '/admin/comissoes'
      preLoaderRoute: typeof AdminComissoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/barbers': {
      id: '/admin/barbers'
      path: '/barbers'
      fullPath: '/admin/barbers'
      preLoaderRoute: typeof AdminBarbersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBarbersRoute: typeof AdminBarbersRoute
  AdminComissoesRoute: typeof AdminComissoesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBarbersRoute: AdminBarbersRoute,
  AdminComissoesRoute: AdminComissoesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BarberRouteChildren {
  BarberAgendaRoute: typeof BarberAgendaRoute
  BarberDashboardRoute: typeof BarberDashboardRoute
  BarberLoginRoute: typeof BarberLoginRoute
}

const BarberRouteChildren: BarberRouteChildren = {
  BarberAgendaRoute: BarberAgendaRoute,
  BarberDashboardRoute: BarberDashboardRoute,
  BarberLoginRoute: BarberLoginRoute,
}

const BarberRouteWithChildren =
  BarberRoute._addFileChildren(BarberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BarberRoute: BarberRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
